// <auto-generated />
namespace Projeto_KB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataValidacionTeste : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataValidacionTeste));
        
        string IMigrationMetadata.Id
        {
            get { return "201711041004054_Data Validacion Teste"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
